services:
  # Nginx
  nginx:
    build:
      context: ./docker
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-lidia}
    restart: unless-stopped
    container_name: nginx
    ports:
      - ${APP_PORT}:8000
    volumes:
      - ./:/var/www/html
      - .env:/var/www/html/.env
    depends_on:
      - php
      - mariadb
      - phpmyadmin
      - mailhog
    networks:
      - lidia-network

  # PHP
  php:
    build:
      context: ./docker
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-lidia}
    restart: always
    container_name: php
    volumes:
      - ./:/var/www/html
      - .env:/var/www/html/.env
    networks:
      - lidia-network

  # MariaDB
  mariadb:
    image: mariadb:11.0.3
    container_name: mariadb
    restart: unless-stopped
    tty: true
    ports:
      - 3307:3306
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      SERVICE_TAGS: dev
      SERVICE_NAME: mariadb
    volumes:
      - lidia-dbdata:/var/lib/mysql
    networks:
      - lidia-network

  # Mailhog
  mailhog:
    platform: linux/amd64
    image: mailhog/mailhog:latest
    container_name: mailhog
    logging:
      driver: "none"
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - lidia-network

  # PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin:5.2.1
    container_name: phpmyadmin
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      PMA_PORT: ${DB_PORT}
    depends_on:
      - mariadb
    ports:
      - 8888:80
    networks:
      - lidia-network

  # Composer
  composer:
    build:
      context: ./docker
      dockerfile: composer.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-lidia}
    container_name: composer
    volumes:
      - ./:/var/www/html
      - .env:/var/www/html/.env
    working_dir: /var/www/html
    depends_on:
      - php
    user: ${USER:-lidia}
    profiles: ["composer"]
    entrypoint: ["composer", "--ignore-platform-reqs"]
    networks:
      - lidia-network

  # NPM
  npm:
    image: node:21.1.0-alpine
    container_name: npm
    volumes:
      - ./:/var/www/html
      - .env:/var/www/html/.env
    ports:
      - 3000:3000
      - 3001:3001
    working_dir: /var/www/html
    profiles: ["npm"]
    entrypoint: ["npm"]
    networks:
      - lidia-network

  # Custom services
  laravel-setup:
    build:
      context: ./docker
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-lidia}
    container_name: laravel-setup
    volumes:
      - ./:/var/www/html
      - .env:/var/www/html/.env
    depends_on:
      - mariadb
    profiles: ["setup"]
    working_dir: /var/www/html
    user: ${USER:-lidia}
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        php artisan key:generate
        php artisan storage:link
        php artisan config:cache
        php artisan event:cache
        php artisan view:cache
        php artisan migrate --seed
    networks:
      - lidia-network

  artisan:
    build:
      context: ./docker
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - USER=${USER:-lidia}
    container_name: artisan
    volumes:
      - ./:/var/www/html
      - .env:/var/www/html/.env
    depends_on:
      - mariadb
    working_dir: /var/www/html
    profiles: ["artisan"]
    user: ${USER:-lidia}
    entrypoint: ["php", "/var/www/html/artisan"]
    networks:
      - lidia-network

# Networks
networks:
  lidia-network:
    driver: bridge

# Volumes
volumes:
  lidia-dbdata:
    driver: local
